---
codecov:
  notify:
    after_n_builds: 1
    require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 70..90

  status:
    project:
      default:
        enabled: true
        threshold: 2%
        if_not_found: success
        if_no_uploads: error
        if_ci_failed: error
    patch:
      default:
        enabled: true
        threshold: 2%
        if_not_found: success
        if_no_uploads: error
        if_ci_failed: error
    changes: false

comment:
  layout: "header, diff"
  behavior: default
  require_changes: false
