---
version: 2.1

stdenv: &stdenv
  environment:
    GOCACHE: &gocache /tmp/go-build
    WORKDIR: &workdir /go/src/github.com/saschagrunert/demo

executors:
  container:
    docker:
      - image: circleci/golang:1.13
        user: circleci
    <<: *stdenv
    working_directory: *workdir

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - lint
      - test
      - vendor

jobs:
  build:
    executor: container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-build-{{ checksum "go.sum" }}
      - run: go version
      - run:
          name: build
          command: make
      - save_cache:
          key: v1-build-{{ checksum "go.sum" }}
          paths:
            - *gocache
      - store_artifacts:
          path: build
          destination: bin

  lint:
    executor: container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-golangci-lint-{{ checksum "go.sum" }}
      - run:
          name: lint
          command: make lint
      - save_cache:
          key: v2-golangci-lint-{{ checksum "go.sum" }}
          paths:
            - *gocache

  test:
    executor: container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-test-{{ checksum "go.sum" }}
      - run:
          name: test
          command: make test
      - run:
          name: code coverage
          command: make codecov
      - store_test_results:
          path: build/junit
      - save_cache:
          key: v1-test-{{ checksum "go.sum" }}
          paths:
            - *gocache
            - build/ginkgo

  vendor:
    executor: container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vendor-{{ checksum "go.sum" }}
      - run:
          name: check vendoring
          command: |
            make vendor
            .circleci/git-status
      - save_cache:
          key: v1-vendor-{{ checksum "go.sum" }}
          paths:
            - /go/pkg
